version: '3.9'

services:
  fnclub:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      sh -c "until pg_isready -h fnclub-db -U postgres; do echo waiting for postgres; sleep 2; done &&
             python /proj/unitysphere/manage.py migrate &&
             python /proj/unitysphere/manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    volumes:
      - .:/proj
      - /proj/bin
    environment:
      POSTGRES_HOST: fnclub-db
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_NAME: postgres


  fnclub-db:
    image: postgres:16-alpine
    environment:
      POSTGRES_PASSWORD: postgres


# прописать в терминале для миграции
# docker-compose exec fnclub makemigrations