# Generated by Django 3.2.23 on 2024-05-13 18:25

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('iata_code', models.CharField(db_index=True, max_length=20, verbose_name='Код города')),
                ('name', models.CharField(max_length=50, verbose_name='Название города')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
            },
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('logo', models.ImageField(default='club/logos/club-icon.png', upload_to='club/logos', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])])),
                ('description', models.TextField(validators=[django.core.validators.MinLengthValidator(200)], verbose_name='Описание')),
                ('email', models.EmailField(max_length=254, verbose_name='Контактный email')),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message="Номер телефона должен быть введен в формате: '+999999999'. Максимум 15 чисел.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Контактный телефон')),
                ('address', models.CharField(blank=True, default='No location', max_length=150, verbose_name='Локация клуба')),
                ('likes_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True, verbose_name='Активность')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('subscribers_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Клуб',
                'verbose_name_plural': 'Клубы',
            },
        ),
        migrations.CreateModel(
            name='ClubCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название категории')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активность')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название мероприятия')),
                ('description', models.TextField(validators=[django.core.validators.MinLengthValidator(100)], verbose_name='Описание')),
                ('event_img', models.ImageField(upload_to='events', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])], verbose_name='Изображение мероприятия')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('event_date', models.DateField(verbose_name='Дата мероприятия')),
                ('old_event_date', models.DateField(blank=True, null=True, verbose_name='Старая дата мероприятия')),
                ('min_age', models.PositiveIntegerField(default=0, verbose_name='Минимальный возраст')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='Местоположение')),
                ('other_conditions', models.TextField(blank=True, null=True, verbose_name='Другие условия')),
                ('club', models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='clubs.club', verbose_name='Клуб')),
            ],
            options={
                'verbose_name': 'Мероприятие',
                'verbose_name_plural': 'Мероприятия',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClubService',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('club', models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='clubs.club', verbose_name='Клуб')),
            ],
            options={
                'verbose_name': 'Услуга клуба',
                'verbose_name_plural': 'Услуги клуба',
            },
        ),
        migrations.AddField(
            model_name='club',
            name='category',
            field=models.ForeignKey(limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clubs', to='clubs.clubcategory', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='club',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clubs.city', verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='club',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_by_users', to=settings.AUTH_USER_MODEL, verbose_name='Нравится'),
        ),
        migrations.AddField(
            model_name='club',
            name='managers',
            field=models.ManyToManyField(blank=True, related_name='co_managed_clubs', to=settings.AUTH_USER_MODEL, verbose_name='Соуправляющие клуба'),
        ),
        migrations.AddField(
            model_name='club',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='members_of_clubs', to=settings.AUTH_USER_MODEL, verbose_name='Члены клуба'),
        ),
        migrations.AddField(
            model_name='club',
            name='subscribers',
            field=models.ManyToManyField(related_name='subscriptions', to='clubs.Club', verbose_name='Подписчики'),
        ),
        migrations.CreateModel(
            name='Ads',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название рекламы')),
                ('description', models.TextField(max_length=1000, verbose_name='Описание')),
                ('ads_img', models.ImageField(upload_to='ads', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])], verbose_name='Изображение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('club', models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, to='clubs.club', verbose_name='Клуб')),
            ],
            options={
                'verbose_name': 'Реклама',
                'verbose_name_plural': 'Рекламы',
                'ordering': ['-created_at'],
            },
        ),
    ]
