# Generated by Django 4.2.7 on 2024-07-03 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='whatsapp_link',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Ссылка на WhatsApp'),
        ),
    ]
