# Generated by Django 4.2.13 on 2024-05-13 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clubcategory',
            name='slug',
        ),
    ]
