# Generated by Django 3.2.23 on 2024-05-06 11:04

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, null=True, unique=True)),
                ('logo', models.ImageField(default='club/logos/club-icon.png', upload_to='club/logos', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])])),
                ('description', models.TextField(validators=[django.core.validators.MinLengthValidator(200)], verbose_name='Описание')),
                ('email', models.EmailField(max_length=254, verbose_name='Контактный email')),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message="Номер телефона должен быть введен в формате: '+999999999'. Максимум 15 чисел.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Контактный телефон')),
                ('address', models.CharField(blank=True, default='No location', max_length=150, verbose_name='Локация клуба')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clubs', to='clubs.clubcategory')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clubs.city')),
                ('co_managers', models.ManyToManyField(blank=True, related_name='co_managed_clubs', to=settings.AUTH_USER_MODEL, verbose_name='Соуправляющие клуба')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='managed_clubs', to=settings.AUTH_USER_MODEL, verbose_name='Управляющий клуба')),
                ('members', models.ManyToManyField(blank=True, related_name='clubs', to=settings.AUTH_USER_MODEL, verbose_name='Члены клуба')),
            ],
            options={
                'verbose_name': 'Клуб',
                'verbose_name_plural': 'Клубы',
            },
        ),
    ]
