# Generated by Django 4.2.13 on 2024-05-22 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_alter_club_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='members_count',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Кол-во участников'),
        ),
        migrations.AlterField(
            model_name='club',
            name='likes_count',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Кол-во лайков'),
        ),
        migrations.AlterField(
            model_name='club',
            name='partners_count',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Кол-во партнеров'),
        ),
    ]
