# Generated by Django 4.2.13 on 2024-05-23 12:28

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clubs', '0004_clubadtype_festival_alter_clubads_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clubads',
            options={'verbose_name': 'Объявление', 'verbose_name_plural': 'Объявления'},
        ),
        migrations.AlterModelOptions(
            name='festival',
            options={'verbose_name': 'Фестиваль', 'verbose_name_plural': 'Фестивали'},
        ),
        migrations.AddField(
            model_name='club',
            name='is_private',
            field=models.BooleanField(default=False, verbose_name='Приватный клуб'),
        ),
        migrations.AddField(
            model_name='festival',
            name='approved_clubs',
            field=models.ManyToManyField(related_name='approved_on_festival', to='clubs.club', verbose_name='Приглашенные клубы'),
        ),
        migrations.AlterField(
            model_name='club',
            name='managers',
            field=models.ManyToManyField(blank=True, related_name='managed_clubs', to=settings.AUTH_USER_MODEL, verbose_name='Управляющие клуба'),
        ),
        migrations.AlterField(
            model_name='clubevent',
            name='max_age',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Максимальный возраст для входа'),
        ),
        migrations.AlterField(
            model_name='clubevent',
            name='min_age',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Минимальный возраст для входа'),
        ),
        migrations.AlterField(
            model_name='festival',
            name='image',
            field=models.ImageField(upload_to='clubs/festival_photo', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])], verbose_name='Фото'),
        ),
        migrations.CreateModel(
            name='FestivalParticipationRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('approved', models.BooleanField(default=None, null=True, verbose_name='Приглашен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='festival_participation_request', to='clubs.club')),
                ('festival', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='clubs.festival')),
            ],
        ),
        migrations.CreateModel(
            name='ClubServiceImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='club/service_images', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])], verbose_name='Фото')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='clubs.clubservice')),
            ],
            options={
                'verbose_name': 'Изображение для услуги клуба',
                'verbose_name_plural': 'Изображения для услуг клуба',
            },
        ),
        migrations.CreateModel(
            name='ClubPartnerShipRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('club_accepter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partnership_receive_requests', to='clubs.club', verbose_name='Принимающий клуб')),
                ('club_requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partnership_send_requests', to='clubs.club', verbose_name='Запрашивающий клуб')),
            ],
        ),
        migrations.CreateModel(
            name='ClubJoinRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('approved', models.BooleanField(default=False, verbose_name='Принят')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_join_requests', to='clubs.club', verbose_name='Клуб')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_join_requests', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
