# Generated by Django 4.2.13 on 2024-05-27 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0006_festival_start_datetime'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='festivalparticipationrequest',
            options={'verbose_name': 'Запрос на участие в фестивале', 'verbose_name_plural': 'Запросы на участие в фестивале'},
        ),
        migrations.AlterField(
            model_name='festival',
            name='approved_clubs',
            field=models.ManyToManyField(blank=True, related_name='approved_on_festival', to='clubs.club', verbose_name='Приглашенные клубы'),
        ),
        migrations.AddConstraint(
            model_name='festivalparticipationrequest',
            constraint=models.UniqueConstraint(fields=('club', 'festival'), name='unique_club_festival_request'),
        ),
    ]
