# Generated by Django 4.2.13 on 2024-05-27 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0007_alter_festivalparticipationrequest_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubjoinrequest',
            name='approved',
            field=models.BooleanField(default=None, null=True, verbose_name='Принят'),
        ),
    ]
