# Generated by Django 4.2.13 on 2024-05-27 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0008_alter_clubjoinrequest_approved'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clubjoinrequest',
            options={'verbose_name': 'Запрос на вступление в клуб', 'verbose_name_plural': 'Запросы на вступление в клуб'},
        ),
        migrations.AddConstraint(
            model_name='clubjoinrequest',
            constraint=models.UniqueConstraint(fields=('user', 'club'), name='unique_user_club_join_request'),
        ),
    ]
