# Generated by Django 4.2.13 on 2024-06-03 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0010_rename_club_clubserviceimage_service'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='club',
            options={'ordering': ('-members_count', '-likes_count', 'name'), 'verbose_name': 'Клуб', 'verbose_name_plural': 'Клубы'},
        ),
        migrations.AddField(
            model_name='clubpartnershiprequest',
            name='approved',
            field=models.BooleanField(default=None, null=True, verbose_name='Принято'),
        ),
    ]
