# Generated by Django 4.2.13 on 2024-07-16 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0011_alter_club_options_clubpartnershiprequest_approved'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clubgalleryphoto',
            options={'ordering': ('-created_at',), 'verbose_name': 'Фото', 'verbose_name_plural': 'Фото'},
        ),
    ]
