# Generated by Django 4.2.13 on 2024-06-26 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='about',
            field=models.TextField(blank=True, null=True, verbose_name='О себе'),
        ),
        migrations.AddField(
            model_name='user',
            name='goals_for_life',
            field=models.TextField(blank=True, null=True, verbose_name='Цели на жизнь'),
        ),
    ]
