# Generated by Django 4.2.13 on 2024-06-26 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_about_user_goals_for_life'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='interests',
            field=models.TextField(blank=True, null=True, verbose_name='Интересы'),
        ),
    ]
