# Generated by Django 4.2.13 on 2024-06-28 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_user_about_remove_user_goals_for_life_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_displayed_in_allies',
            field=models.BooleanField(default=False),
        ),
    ]
